#on:
#  schedule:
#    - cron: '50 2 * * *'
on: workflow_dispatch
    
jobs:
  update_api_data:
    name: Update data for API
    runs-on: ubuntu-latest
    permissions: write-all
    env:
        key: error
    steps:
      - uses: ./.github/actions/get_api_data.yml
        id: get_data
      - uses: wow-actions/update-file@v1.2.0
        with:
          # Your GitHub token for authentication.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # File path to update
          path: key.xml
          # Content to update the file
          content: ${{ steps.get_data.outputs.* }}
          # Commit message when update the file
          commit_message: Update API data
